apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatops-backend
  labels:
    app: chatops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatops
  template:
    metadata:
      labels:
        app: chatops
    spec:
      containers:
      - name: chatops-container
        image: your-dockerhub-username/chatops-backend:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: ENV
          value: "production"
