apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatops-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatops
  template:
    metadata:
      labels:
        app: chatops
    spec:
      containers:
      - name: chatops-container
        image: your-docker-image:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"