apiVersion: v1
kind: Service
metadata:
  name: chatops-service
spec:
  selector:
    app: chatops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Use NodePort for local testing
